import os


env = SConscript('godot-cpp/SConstruct')


#env.Append(CPPPATH="src/")

include_paths = ["src/"]
for root, dirs, files in os.walk("src"):
    for d in dirs:
        include_paths.append(os.path.join(root, d))

env.Append(CPPPATH=include_paths)

trymakingtpc = []
for root, dirs, files in os.walk("src"):
    for file in files:
        if file.endswith(".cpp"):
            trymakingtpc.append(os.path.join(root, file))


if env['platform'] == 'linux':
    trymakingtpclibpath = '../addons/TryMakingTPC{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])

    env.Append(CXXFLAGS=["-fPIC", "-Wall", "-std=c++17", "-fvisibility=default"])
    env.Append(LINKFLAGS=["-shared"])

    trymakingtpcsharedlib = env.SharedLibrary(trymakingtpclibpath,trymakingtpc)
    Default(trymakingtpcsharedlib)
elif env['platform'] == 'windows':
    trymakingtpclibpath = '../addons/TryMakingTPC{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])  # SHLIBSUFFIX обычно .dll

    trymakingtpcsharedlib = env.SharedLibrary(trymakingtpclibpath, trymakingtpc)
    Default(trymakingtpcsharedlib)
